<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cs_youtube_data"
 *
 * Auto generated by Extension Builder 2014-12-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '[clickstorm] Youtube Data V3',
	'description' => 'Displays a youtube channel on your page',
	'category' => 'plugin',
	'author' => 'Andreas Kirilow - clickstorm GmbH',
	'author_email' => 'kirilow@clickstorm.de',
    'author_company' => 'clickstorm GmbH',
	'state' => 'stable',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '10.4.0 - 10.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
